version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=dib1o&f(0kupe2)-u*p*@kv30_!@vrdf1%%(k%i&w2q$$*75pvn
      - DEBUG=True
      - SENDGRID_API_KEY=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
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
